-- Kept as a no-op for migration-history compatibility.
-- `public.admins` was moved into 20260809000100_create_app_schema.sql so a
-- clean reset creates the local identity table before its foreign-key users.
